parameters:
    web_security:
        headers:
            content_security_policy:
                default-src: ["'self'"]
                script-src: ["'self'", "'unsafe-inline'", "'unsafe-eval'", "https://cdnjs.cloudflare.com", "https://code.jquery.com"]
                style-src: ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"]
                img-src: ["'self'", "data:", "https:"]
                font-src: ["'self'", "https://fonts.gstatic.com"]
                connect-src: ["'self'"]
                frame-src: ["'self'"]
                object-src: ["'none'"]
                media-src: ["'self'"]
                base-uri: ["'self'"]
                form-action: ["'self'"]
                frame-ancestors: ["'none'"] 